[2024-04-26T17:23:14.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:23:14.432+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [queued]>
[2024-04-26T17:23:14.439+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [queued]>
[2024-04-26T17:23:14.439+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:23:14.450+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.transform> on 2024-04-04 22:00:00+00:00
[2024-04-26T17:23:14.459+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=829) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:23:14.460+0000] {standard_task_runner.py:63} INFO - Started process 837 to run task
[2024-04-26T17:23:14.459+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'etl.transform', 'backfill__2024-04-04T22:00:00+00:00', '--job-id', '330', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmp52c_jw2g']
[2024-04-26T17:23:14.461+0000] {standard_task_runner.py:91} INFO - Job 330: Subtask etl.transform
[2024-04-26T17:23:14.501+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:23:14.573+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='etl.transform' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-04T22:00:00+00:00'
[2024-04-26T17:23:14.574+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:23:14.584+0000] {tasks.py:52} INFO - Transforming location data...
[2024-04-26T17:23:14.594+0000] {LocationConnector.py:104} ERROR - Error transforming DataFrame: 'NoneType' object has no attribute 'split'
[2024-04-26T17:23:14.594+0000] {tasks.py:54} INFO - Location data transformation complete.
[2024-04-26T17:23:14.594+0000] {tasks.py:57} INFO - Transforming air quality data...
[2024-04-26T17:23:14.600+0000] {AirQualityConnector.py:101} INFO - Successfully transformed DataFrame
[2024-04-26T17:23:14.600+0000] {AirQualityConnector.py:102} INFO - Shape of transformed DataFrame: (46, 11)
[2024-04-26T17:23:14.600+0000] {tasks.py:59} INFO - Air quality data transformation complete.
[2024-04-26T17:23:14.600+0000] {tasks.py:62} INFO - Merging location and air quality data...
[2024-04-26T17:23:14.600+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:23:14.601+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 63, in transform_data
    merged_data = pd.merge(transformed_location_data, transformed_air_quality_data, on="latitude", how="inner")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 791, in __init__
    ) = self._get_merge_keys()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1287, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'latitude'
[2024-04-26T17:23:14.610+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_pipeline, task_id=etl.transform, execution_date=20240404T220000, start_date=20240426T172314, end_date=20240426T172314
[2024-04-26T17:23:14.618+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 330 for task etl.transform ('latitude'; 837)
[2024-04-26T17:23:14.634+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T17:23:14.650+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:23:14.651+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-26T17:43:55.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:43:55.405+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [queued]>
[2024-04-26T17:43:55.411+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [queued]>
[2024-04-26T17:43:55.411+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:43:55.420+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.transform> on 2024-04-04 22:00:00+00:00
[2024-04-26T17:43:55.429+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1842) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:43:55.430+0000] {standard_task_runner.py:63} INFO - Started process 1843 to run task
[2024-04-26T17:43:55.429+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'etl.transform', 'backfill__2024-04-04T22:00:00+00:00', '--job-id', '403', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmprgnblzvr']
[2024-04-26T17:43:55.431+0000] {standard_task_runner.py:91} INFO - Job 403: Subtask etl.transform
[2024-04-26T17:43:55.463+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.etl.transform backfill__2024-04-04T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:43:55.525+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='etl.transform' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-04T22:00:00+00:00'
[2024-04-26T17:43:55.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:43:55.534+0000] {tasks.py:52} INFO - Transforming location data...
[2024-04-26T17:43:55.545+0000] {LocationConnector.py:100} INFO - Successfully transformed DataFrame
[2024-04-26T17:43:55.545+0000] {LocationConnector.py:101} INFO - Shape of transformed DataFrame: (3, 8)
[2024-04-26T17:43:55.545+0000] {tasks.py:54} INFO - Location data transformation complete.
[2024-04-26T17:43:55.546+0000] {tasks.py:57} INFO - Transforming air quality data...
[2024-04-26T17:43:55.550+0000] {AirQualityConnector.py:101} INFO - Successfully transformed DataFrame
[2024-04-26T17:43:55.550+0000] {AirQualityConnector.py:102} INFO - Shape of transformed DataFrame: (69, 11)
[2024-04-26T17:43:55.550+0000] {tasks.py:59} INFO - Air quality data transformation complete.
[2024-04-26T17:43:55.550+0000] {tasks.py:62} INFO - Merging location and air quality data...
[2024-04-26T17:43:55.552+0000] {tasks.py:64} INFO - Location and air quality data merge complete.
[2024-04-26T17:43:55.553+0000] {tasks.py:70} INFO - Saving transformed data to CSV...
[2024-04-26T17:43:55.555+0000] {tasks.py:72} INFO - Transformed data saved to CSV.
[2024-04-26T17:43:55.555+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T17:43:55.555+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:43:55.562+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=air_quality_pipeline, task_id=etl.transform, execution_date=20240404T220000, start_date=20240426T174355, end_date=20240426T174355
[2024-04-26T17:43:55.602+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T17:43:55.623+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:43:55.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
