[2024-04-26T16:31:51.946+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T16:31:51.967+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T16:31:51.972+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T16:31:51.973+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-26T16:31:51.980+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_air_quality_alerts> on 2024-02-05 00:00:00+00:00
[2024-04-26T16:31:51.991+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2410) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T16:31:51.990+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'send_air_quality_alerts', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmp8mb9xvcc']
[2024-04-26T16:31:51.991+0000] {standard_task_runner.py:63} INFO - Started process 2412 to run task
[2024-04-26T16:31:51.991+0000] {standard_task_runner.py:91} INFO - Job 293: Subtask send_air_quality_alerts
[2024-04-26T16:31:52.023+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [running]> on host cf1d83d83b27
[2024-04-26T16:31:52.078+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='send_air_quality_alerts' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-04-26T16:31:52.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T16:31:52.088+0000] {tasks.py:85} INFO - Generating air quality alerts...
[2024-04-26T16:31:52.092+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T16:31:52.092+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 86, in send_air_quality_alerts
    alert_message = air_quality_alerts()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/air_quality_alerts.py", line 70, in air_quality_alerts
    config = load_config("alert_config.json")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/air_quality_alerts.py", line 18, in load_config
    with open(config_file) as file:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'alert_config.json'
[2024-04-26T16:31:52.099+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pipeline, task_id=send_air_quality_alerts, execution_date=20240205T000000, start_date=20240426T163151, end_date=20240426T163152
[2024-04-26T16:31:52.106+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 293 for task send_air_quality_alerts ([Errno 2] No such file or directory: 'alert_config.json'; 2412)
[2024-04-26T16:31:52.124+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T16:31:52.138+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T16:31:52.138+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-26T16:39:19.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T16:39:19.262+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T16:39:19.268+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T16:39:19.268+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-26T16:39:19.397+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_air_quality_alerts> on 2024-02-05 00:00:00+00:00
[2024-04-26T16:39:19.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'send_air_quality_alerts', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpcv13ucij']
[2024-04-26T16:39:19.407+0000] {standard_task_runner.py:91} INFO - Job 301: Subtask send_air_quality_alerts
[2024-04-26T16:39:19.407+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T16:39:19.407+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2024-04-26T16:39:19.441+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.send_air_quality_alerts scheduled__2024-02-05T00:00:00+00:00 [running]> on host 5fdceac7b2c7
[2024-04-26T16:39:19.496+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='send_air_quality_alerts' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-04-26T16:39:19.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T16:39:19.506+0000] {tasks.py:85} INFO - Generating air quality alerts...
[2024-04-26T16:39:19.514+0000] {tasks.py:88} INFO - Sending air quality alerts via email...
[2024-04-26T16:39:20.869+0000] {tasks.py:90} INFO - Air quality alerts sent via email.
[2024-04-26T16:39:20.870+0000] {tasks.py:93} INFO - Cleaning up temporary files...
[2024-04-26T16:39:20.870+0000] {tasks.py:96} INFO - Temporary files cleaned up.
[2024-04-26T16:39:20.871+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T16:39:20.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T16:39:20.880+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=send_air_quality_alerts, execution_date=20240205T000000, start_date=20240426T163919, end_date=20240426T163920
[2024-04-26T16:39:20.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T16:39:20.957+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T16:39:20.957+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
