[2024-04-24T22:03:11.083+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T22:03:11.106+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_pipe.extract manual__2024-04-24T21:50:25.883178+00:00 [queued]>
[2024-04-24T22:03:11.228+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_pipe.extract manual__2024-04-24T21:50:25.883178+00:00 [queued]>
[2024-04-24T22:03:11.229+0000] {taskinstance.py:2303} INFO - Starting attempt 8 of 8
[2024-04-24T22:03:11.238+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract> on 2024-04-24 21:50:25.883178+00:00
[2024-04-24T22:03:11.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_pipe', 'extract', 'manual__2024-04-24T21:50:25.883178+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmposerab3x']
[2024-04-24T22:03:11.247+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask extract
[2024-04-24T22:03:11.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=783) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T22:03:11.248+0000] {standard_task_runner.py:63} INFO - Started process 785 to run task
[2024-04-24T22:03:11.277+0000] {task_command.py:426} INFO - Running <TaskInstance: test_pipe.extract manual__2024-04-24T21:50:25.883178+00:00 [running]> on host 7dc195e25eb1
[2024-04-24T22:03:11.338+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_pipe' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T21:50:25.883178+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T21:50:25.883178+00:00'
[2024-04-24T22:03:11.339+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T22:03:11.350+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T22:03:11.350+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 60, in test
    date_object = datetime.strptime(params, "%Y-%m-%d %H:%M:%S")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-04-24' does not match format '%Y-%m-%d %H:%M:%S'
[2024-04-24T22:03:11.358+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_pipe, task_id=extract, execution_date=20240424T215025, start_date=20240424T220311, end_date=20240424T220311
[2024-04-24T22:03:11.365+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 106 for task extract (time data '2024-04-24' does not match format '%Y-%m-%d %H:%M:%S'; 785)
[2024-04-24T22:03:11.382+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-24T22:03:11.394+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T22:03:11.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
