[2024-04-26T00:07:16.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T00:07:16.281+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.test_alert scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T00:07:16.288+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.test_alert scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-04-26T00:07:16.289+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-26T00:07:16.416+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_alert> on 2024-02-05 00:00:00+00:00
[2024-04-26T00:07:16.425+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6511) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T00:07:16.425+0000] {standard_task_runner.py:63} INFO - Started process 6513 to run task
[2024-04-26T00:07:16.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'test_alert', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpkugri32x']
[2024-04-26T00:07:16.426+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask test_alert
[2024-04-26T00:07:16.458+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.test_alert scheduled__2024-02-05T00:00:00+00:00 [running]> on host cf1d83d83b27
[2024-04-26T00:07:16.515+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='test_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-04-26T00:07:16.516+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T00:07:16.542+0000] {logging_mixin.py:188} INFO - Hay un problema
[2024-04-26T00:07:16.543+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T00:07:16.543+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T00:07:16.548+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=test_alert, execution_date=20240205T000000, start_date=20240426T000716, end_date=20240426T000716
[2024-04-26T00:07:16.598+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T00:07:16.609+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T00:07:16.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
