[2024-04-25T22:09:41.185+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T22:09:41.211+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:09:41.217+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:09:41.217+0000] {taskinstance.py:2303} INFO - Starting attempt 10 of 10
[2024-04-25T22:09:41.225+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-04-25 21:26:34.912203+00:00
[2024-04-25T22:09:41.233+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2131) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T22:09:41.234+0000] {standard_task_runner.py:63} INFO - Started process 2132 to run task
[2024-04-25T22:09:41.233+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mi_dag', 'branch_task', 'manual__2024-04-25T21:26:34.912203+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmpb9ydr1jr']
[2024-04-25T22:09:41.234+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask branch_task
[2024-04-25T22:09:41.270+0000] {task_command.py:426} INFO - Running <TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [running]> on host cf1d83d83b27
[2024-04-25T22:09:41.337+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mi_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T21:26:34.912203+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T21:26:34.912203+00:00'
[2024-04-25T22:09:41.338+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T22:09:41.347+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-25T22:09:41.355+0000] {logging_mixin.py:188} INFO - Estado de la tarea anterior: tarea_fallida
[2024-04-25T22:09:41.355+0000] {python.py:237} INFO - Done. Returned value was: tarea_fallida
[2024-04-25T22:09:41.355+0000] {branch.py:36} INFO - Branch into tarea_fallida
[2024-04-25T22:09:41.355+0000] {skipmixin.py:178} INFO - Following branch tarea_fallida
[2024-04-25T22:09:41.369+0000] {skipmixin.py:246} INFO - Skipping tasks [('tarea_exitosa', -1)]
[2024-04-25T22:09:41.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T22:09:41.400+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mi_dag, task_id=branch_task, execution_date=20240425T212634, start_date=20240425T220941, end_date=20240425T220941
[2024-04-25T22:09:41.447+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T22:09:41.465+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T22:09:41.467+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
