[2024-04-25T22:34:29.366+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T22:34:29.390+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:34:29.395+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T22:34:29.396+0000] {taskinstance.py:2303} INFO - Starting attempt 14 of 14
[2024-04-25T22:34:29.405+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-04-25 21:26:34.912203+00:00
[2024-04-25T22:34:29.412+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3064) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T22:34:29.413+0000] {standard_task_runner.py:63} INFO - Started process 3065 to run task
[2024-04-25T22:34:29.412+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mi_dag', 'branch_task', 'manual__2024-04-25T21:26:34.912203+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmpj_9xq9pd']
[2024-04-25T22:34:29.414+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask branch_task
[2024-04-25T22:34:29.446+0000] {task_command.py:426} INFO - Running <TaskInstance: mi_dag.branch_task manual__2024-04-25T21:26:34.912203+00:00 [running]> on host cf1d83d83b27
[2024-04-25T22:34:29.510+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mi_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T21:26:34.912203+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T21:26:34.912203+00:00'
[2024-04-25T22:34:29.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T22:34:29.519+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-25T22:34:29.527+0000] {logging_mixin.py:188} INFO - Estado de la tarea anterior: None
[2024-04-25T22:34:29.527+0000] {python.py:237} INFO - Done. Returned value was: tarea_fallida
[2024-04-25T22:34:29.527+0000] {branch.py:36} INFO - Branch into tarea_fallida
[2024-04-25T22:34:29.528+0000] {skipmixin.py:178} INFO - Following branch tarea_fallida
[2024-04-25T22:34:29.540+0000] {skipmixin.py:246} INFO - Skipping tasks [('tarea_exitosa', -1)]
[2024-04-25T22:34:29.559+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T22:34:29.573+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mi_dag, task_id=branch_task, execution_date=20240425T212634, start_date=20240425T223429, end_date=20240425T223429
[2024-04-25T22:34:29.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T22:34:29.645+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T22:34:29.646+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
