[2024-04-26T00:00:02.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T00:00:02.436+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mi_dag.branch_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T00:00:02.441+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mi_dag.branch_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T00:00:02.441+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-26T00:00:02.451+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-04-25 00:00:00+00:00
[2024-04-26T00:00:02.457+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6235) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T00:00:02.458+0000] {standard_task_runner.py:63} INFO - Started process 6236 to run task
[2024-04-26T00:00:02.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mi_dag', 'branch_task', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmpwmkqnvag']
[2024-04-26T00:00:02.459+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask branch_task
[2024-04-26T00:00:02.491+0000] {task_command.py:426} INFO - Running <TaskInstance: mi_dag.branch_task scheduled__2024-04-25T00:00:00+00:00 [running]> on host cf1d83d83b27
[2024-04-26T00:00:02.552+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mi_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-26T00:00:02.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T00:00:02.563+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-26T00:00:02.570+0000] {logging_mixin.py:188} INFO - Estado de la tarea anterior: None
[2024-04-26T00:00:02.570+0000] {python.py:237} INFO - Done. Returned value was: tarea_fallida
[2024-04-26T00:00:02.571+0000] {branch.py:36} INFO - Branch into tarea_fallida
[2024-04-26T00:00:02.571+0000] {skipmixin.py:178} INFO - Following branch tarea_fallida
[2024-04-26T00:00:02.586+0000] {skipmixin.py:246} INFO - Skipping tasks [('tarea_exitosa', -1)]
[2024-04-26T00:00:02.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T00:00:02.621+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mi_dag, task_id=branch_task, execution_date=20240425T000000, start_date=20240426T000002, end_date=20240426T000002
[2024-04-26T00:00:02.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T00:00:02.691+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T00:00:02.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
