[2024-04-26T17:22:49.425+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:22:49.461+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:22:49.470+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:22:49.470+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:22:49.482+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.extract> on 2024-04-02 22:00:00+00:00
[2024-04-26T17:22:49.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=801) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:22:49.495+0000] {standard_task_runner.py:63} INFO - Started process 809 to run task
[2024-04-26T17:22:49.494+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'etl.extract', 'backfill__2024-04-02T22:00:00+00:00', '--job-id', '316', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmps6lkbxa1']
[2024-04-26T17:22:49.496+0000] {standard_task_runner.py:91} INFO - Job 316: Subtask etl.extract
[2024-04-26T17:22:49.567+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:22:49.664+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='etl.extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-02T22:00:00+00:00'
[2024-04-26T17:22:49.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:22:49.676+0000] {tasks.py:35} INFO - Extracting location...
[2024-04-26T17:22:49.679+0000] {LocationConnector.py:70} INFO - Extracting data for: Guadalajara
[2024-04-26T17:22:50.105+0000] {LocationConnector.py:53} ERROR - Error querying the API 429 Client Error: Too Many Requests for url: https://us1.locationiq.com/v1/search/structured?city=Guadalajara&format=json&countrycodes=MX&key=pk.eb06967d04dbcf43f95529ade5970ed9
[2024-04-26T17:22:51.107+0000] {LocationConnector.py:70} INFO - Extracting data for: Monterrey
[2024-04-26T17:22:51.497+0000] {LocationConnector.py:53} ERROR - Error querying the API 429 Client Error: Too Many Requests for url: https://us1.locationiq.com/v1/search/structured?city=Monterrey&format=json&countrycodes=MX&key=pk.eb06967d04dbcf43f95529ade5970ed9
[2024-04-26T17:22:53.499+0000] {LocationConnector.py:70} INFO - Extracting data for: Mexico City
[2024-04-26T17:22:53.848+0000] {LocationConnector.py:53} ERROR - Error querying the API 429 Client Error: Too Many Requests for url: https://us1.locationiq.com/v1/search/structured?city=Mexico+City&format=json&countrycodes=MX&key=pk.eb06967d04dbcf43f95529ade5970ed9
[2024-04-26T17:22:56.852+0000] {LocationConnector.py:78} INFO - Successfully Extracted Location data: (3, 0)
[2024-04-26T17:22:56.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:22:56.853+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/tasks.py", line 36, in extract_location_and_air_quality
    location_metadata = location_api_connector.extract_location()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/LocationConnector.py", line 80, in extract_location
    return df_city[["lat", "lon"]]
           ~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6114, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6175, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['lat', 'lon'], dtype='object')] are in the [columns]"
[2024-04-26T17:22:56.867+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_pipeline, task_id=etl.extract, execution_date=20240402T220000, start_date=20240426T172249, end_date=20240426T172256
[2024-04-26T17:22:56.876+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 316 for task etl.extract ("None of [Index(['lat', 'lon'], dtype='object')] are in the [columns]"; 809)
[2024-04-26T17:22:56.915+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T17:22:56.936+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:22:56.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-26T17:32:11.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:32:11.711+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:32:11.715+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:32:11.715+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:32:11.723+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.extract> on 2024-04-02 22:00:00+00:00
[2024-04-26T17:32:11.731+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1251) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:32:11.731+0000] {standard_task_runner.py:63} INFO - Started process 1252 to run task
[2024-04-26T17:32:11.731+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'etl.extract', 'backfill__2024-04-02T22:00:00+00:00', '--job-id', '378', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpxcv4f0ac']
[2024-04-26T17:32:11.732+0000] {standard_task_runner.py:91} INFO - Job 378: Subtask etl.extract
[2024-04-26T17:32:11.764+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:32:11.826+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='etl.extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-02T22:00:00+00:00'
[2024-04-26T17:32:11.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:32:11.835+0000] {tasks.py:35} INFO - Extracting location...
[2024-04-26T17:32:11.837+0000] {LocationConnector.py:70} INFO - Extracting data for: Guadalajara
[2024-04-26T17:32:14.310+0000] {LocationConnector.py:70} INFO - Extracting data for: Monterrey
[2024-04-26T17:32:16.717+0000] {LocationConnector.py:70} INFO - Extracting data for: Mexico City
[2024-04-26T17:32:20.125+0000] {LocationConnector.py:78} INFO - Successfully Extracted Location data: (3, 12)
[2024-04-26T17:32:20.126+0000] {tasks.py:37} INFO - Location extraction complete.
[2024-04-26T17:32:20.127+0000] {tasks.py:40} INFO - Extracting air quality data...
[2024-04-26T17:32:28.669+0000] {AirQualityConnector.py:85} INFO - Successfully Extracted air quality data: (69, 11)
[2024-04-26T17:32:28.669+0000] {tasks.py:42} INFO - Air quality data extraction complete.
[2024-04-26T17:32:28.670+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T17:32:28.670+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:32:28.677+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=air_quality_pipeline, task_id=etl.extract, execution_date=20240402T220000, start_date=20240426T173211, end_date=20240426T173228
[2024-04-26T17:32:28.706+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T17:32:28.725+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:32:28.726+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-26T17:40:32.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T17:40:32.993+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:40:32.999+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [queued]>
[2024-04-26T17:40:32.999+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T17:40:33.008+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): etl.extract> on 2024-04-02 22:00:00+00:00
[2024-04-26T17:40:33.017+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1585) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T17:40:33.018+0000] {standard_task_runner.py:63} INFO - Started process 1586 to run task
[2024-04-26T17:40:33.017+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_pipeline', 'etl.extract', 'backfill__2024-04-02T22:00:00+00:00', '--job-id', '395', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/air_quality_dag.py', '--cfg-path', '/tmp/tmpkckrnz9f']
[2024-04-26T17:40:33.019+0000] {standard_task_runner.py:91} INFO - Job 395: Subtask etl.extract
[2024-04-26T17:40:33.053+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_pipeline.etl.extract backfill__2024-04-02T22:00:00+00:00 [running]> on host 4718ecf2379c
[2024-04-26T17:40:33.120+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_pipeline' AIRFLOW_CTX_TASK_ID='etl.extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-04-02T22:00:00+00:00'
[2024-04-26T17:40:33.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T17:40:33.130+0000] {tasks.py:35} INFO - Extracting location...
[2024-04-26T17:40:33.132+0000] {LocationConnector.py:70} INFO - Extracting data for: Guadalajara
[2024-04-26T17:40:35.613+0000] {LocationConnector.py:70} INFO - Extracting data for: Monterrey
[2024-04-26T17:40:38.025+0000] {LocationConnector.py:70} INFO - Extracting data for: Mexico City
[2024-04-26T17:40:40.448+0000] {LocationConnector.py:78} INFO - Successfully Extracted Location data: (3, 12)
[2024-04-26T17:40:40.449+0000] {tasks.py:37} INFO - Location extraction complete.
[2024-04-26T17:40:40.450+0000] {tasks.py:40} INFO - Extracting air quality data...
[2024-04-26T17:40:47.080+0000] {AirQualityConnector.py:85} INFO - Successfully Extracted air quality data: (69, 11)
[2024-04-26T17:40:47.080+0000] {tasks.py:42} INFO - Air quality data extraction complete.
[2024-04-26T17:40:47.081+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T17:40:47.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T17:40:47.091+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=air_quality_pipeline, task_id=etl.extract, execution_date=20240402T220000, start_date=20240426T174032, end_date=20240426T174047
[2024-04-26T17:40:47.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T17:40:47.175+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-26T17:40:47.176+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
