[2024-04-25T21:36:05.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T21:36:05.197+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mi_dag.anterior_tarea manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T21:36:05.203+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mi_dag.anterior_tarea manual__2024-04-25T21:26:34.912203+00:00 [queued]>
[2024-04-25T21:36:05.203+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-25T21:36:05.214+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): anterior_tarea> on 2024-04-25 21:26:34.912203+00:00
[2024-04-25T21:36:05.221+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=923) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T21:36:05.222+0000] {standard_task_runner.py:63} INFO - Started process 924 to run task
[2024-04-25T21:36:05.221+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mi_dag', 'anterior_tarea', 'manual__2024-04-25T21:26:34.912203+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/air_quality/test.py', '--cfg-path', '/tmp/tmppadsoyq2']
[2024-04-25T21:36:05.223+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask anterior_tarea
[2024-04-25T21:36:05.258+0000] {task_command.py:426} INFO - Running <TaskInstance: mi_dag.anterior_tarea manual__2024-04-25T21:26:34.912203+00:00 [running]> on host cf1d83d83b27
[2024-04-25T21:36:05.321+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mi_dag' AIRFLOW_CTX_TASK_ID='anterior_tarea' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T21:26:34.912203+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T21:26:34.912203+00:00'
[2024-04-25T21:36:05.322+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T21:36:05.332+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T21:36:05.332+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/air_quality/test.py", line 8, in tes
    raise ValueError("Error: porque quiero")
ValueError: Error: porque quiero
[2024-04-25T21:36:05.339+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mi_dag, task_id=anterior_tarea, execution_date=20240425T212634, start_date=20240425T213605, end_date=20240425T213605
[2024-04-25T21:36:05.347+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 117 for task anterior_tarea (Error: porque quiero; 924)
[2024-04-25T21:36:05.355+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-25T21:36:05.373+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-25T21:36:05.375+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
